# Generated by Django 5.1.1 on 2024-10-08 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tematica',
            new_name='CategoriaTematica',
        ),
        migrations.RenameModel(
            old_name='Libro_Tematica',
            new_name='LibroUsuario',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='lectura',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ranking_anual',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='ranking_anual',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_prestamo',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='año_publicacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='numero_paginas',
        ),
        migrations.RemoveField(
            model_name='librousuario',
            name='tematica',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_devolucion',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='usuario_prestador',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='usuario_prestatario',
        ),
        migrations.AddField(
            model_name='libro',
            name='archivo',
            field=models.FileField(default='path/to/default/file.pdf', upload_to='libros/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(default='Autor Desconocido', max_length=200),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='libro',
            name='tematica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.categoriatematica'),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo',
            field=models.CharField(default='Título por defecto', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='total_paginas',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librousuario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='DatoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginas_leidas', models.PositiveIntegerField(default=0)),
                ('porcentaje_lectura', models.FloatField(default=0.0)),
                ('puntuacion', models.IntegerField(blank=True, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RankingAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('puntuacion_media', models.FloatField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.libro')),
            ],
            options={
                'unique_together': {('año', 'libro')},
            },
        ),
        migrations.DeleteModel(
            name='Lectura',
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
        migrations.DeleteModel(
            name='Ranking_Anual',
        ),
    ]
