# Generated by Django 5.1.1 on 2024-10-10 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_tematica_categoriatematica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librousuario',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='librousuario',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='rankinganual',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rankinganual',
            name='libro',
        ),
        migrations.AddField(
            model_name='libro',
            name='en_prestamo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='usuarios',
            field=models.ManyToManyField(related_name='prestamos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='libro',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='libros/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros_propios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='libro',
            name='total_paginas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ISBNLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isbn_libro', to='gestion.libro')),
                ('tematica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.categoriatematica')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina_actual', models.PositiveIntegerField(default=0)),
                ('porcentaje_lectura', models.FloatField(default=0.0)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PuntuacionLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(default=0)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DatoUsuario',
        ),
        migrations.DeleteModel(
            name='LibroUsuario',
        ),
        migrations.DeleteModel(
            name='RankingAnual',
        ),
    ]
